spring:
  profiles:
    # 默认激活 dev 环境   dev prod
    active: dev
jwt:
  # 签发人
  issuer: juhe
  # 秘钥
  secret: cVKQ4ifhJpqnhzJE4d4CVDuaBH7wbOVeoiuqTnqrNZjjoElXPmivU6ctuHIjMAqFgPxIGaPAz/m8WjTrpNaRJA==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer


